apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: mysecret
spec:
  encryptedData:
    foo: AgB2NlSL4yZsoLjFazOkeKmmi1dCV7GTTlZwqyuuUmZZ7vfUYqg2qDtj7gvv7SDduAUfyP4lF6NfJyS+TAEqV+PKCo7Nir+T3XiJE1HQ6cNWnfceBJSn3CelQMDJ3Evn9uE4yG6mwo9q/HfOBZufWCvlQlaK/KPYoEtuhdK3453q/TBZTCmehpfwNFUmtH+XTR1DU0IMJmWS0CO+PlKF4W50uAujBtRf2sHIP2m5Vv8aRkEwIPpdWtxRWilWE/aquClQbZfj98UuLg5kDGZKLrMPvv++497dKiftGCJmN2dURwnqHxk5nt0aAf2Y9qh2u15tD55C3n1xQLoHmHSSnorVp0V+Btpzr2jixn6F2V7iqp0wrLdG7q6Kmz0NeMBP/DcHxsvQmcgDFsK02l1U9aRuBTUWnhQQPTiHFVS5x0vmO1ac5YjLZXOkOVphph9jiPKzue7kLfrtkPHjPJslNzCKge8BiV0Scsy3L0rJtukYUa5v2fwXIc2CM+etp6MUTDVpNzUGBWTMm1LgoR69CQMiBeFTki5yhZV/EvAqKAbHsSRXvnchiRkHpPM/x8JLj+Y4QZggtawa9SfP0X8LSFGENac3QzdcF2lq+qNU20xasqFZqxDkjvvN6Erxh4CwgYvM6YVYZi8vX9e03QGfhq3/LEb6LGsGTQi1mGIywHC091bU3AMEfSOAFsba17WpBlH4i+w=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: mysecret