apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: demo-kus
  namespace: demo-kustomize
spec:
  encryptedData:
    password: AgBxfRAIZUePAq7IAiSjecGxlkGKeXNbNrFklxqG0gITpUr+UwTByvoJcdDi/cgfbTMXufyfV9d2Szm9asmT1XOtY6G2dYYJpceqQpTB5QrGbTh40nhHqHgOLN/p9FOD6x9SQp1tPKAlCvP9ZsSLfdUVqaxkwHuahCkqN8bkoSzBfDyIzTJf+YSvSAeUH/4oRgJiP1N+EOmTeKjAlHj+tKwUiFCdN4bOmo9ZVy30hv7n1GKqxj7vsZAnCMvqbDDdcMxkrtHFk00jBaqosISRh7oHaIPRuS8OkMq5uELyqIjH1ETPmHLvh+PDj6vuMkFrjiKeVMbYyIg35pVsJecZd4YlVvPqcus+ZTYiSzdAiXXY3vBy/oUvhM3jpYL11Js7L3XPEK7N3PtsEY4AqNYRCNlFHdTMuva/fsQqR6mPqjHofTEqK8WqCnCtnHTsmJRxAgSGf7/0NJwLUDcxBdsG2adczcdHUOlA7OtkK/ij0RS2tj68BES2e7GbE0WNmI48Nxsrav2F0n25+JdDArjG/YEf+l6mspkqmtRBu2G6qnA8WJFVeQL0feNaEp9kzMNRGFHHUoEHA3CtMHqzVmFVIHk4pJfw5Gg4zb/arzLKrmJj/82kbcS2QdCw1aijBiTLI4sdrqme7y8UEmX0QvSLERKo1tVVh/HrxlfZXTwr0e3wzB666OkT0kjyQbD9wlmjY6Qj5QYjg4kxnlkoEXXgiOtp
  template:
    metadata:
      creationTimestamp: null
      name: demo-kus
      namespace: demo-kustomize