apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: mysecret
spec:
  encryptedData:
    foo: AgC1s44ugLGM9TnQqwLZ+nIdhdJf0WfxZ/b/ZlIzZPvLtg51vBJQDvM28UZykuJZiweGG+7alch6c/8FeaoV82qPE+TPicczconvRvsuexUBr946CpxT8WyNlir4mYIxEzMumcAvt/2Eqg+S9+ckn9LgH5mpakz97wiPD3jQsOvpRq0FE0aDbyRhH3atOoEK1+aqKOavT0p88JBd19Lu/y43aMQtfjCkkWhbCB50eLfXz2wVtwPRlC57o38Pa6X6qr7qEaEbf0sSyU1G9YMRNJYb2uqDXc6oxvC6mJJleMU0YvItUSS0/itgUXyXBnVQdPoUJBM57pQ0tekVJlTDSywt6Nuy5gEOyuh1zTGxsVF4tv0zSbo5gl2M9yzp17CLvQnEnvzEodTETnQjRTUafXJcuk8GgzU0Ojns1Z/u1vMy8Vgg4CthDnLe7ASh9DgOiIGsCQMmW2G38VkiNyWUDFI+ed8BwnXB+yws0hVT0jYzrVsXgsfWbiO7/7udWYHUGZd9/vXXKFLP0vgVlN/PSJCat73kB31J/oeUYDZ0aantgJT0ZrCRpDAckkWnMqbyJPXopOG5DPMT01R508a0ERIkspYrEHVFmUshHemUwKFrbRJ4wtfuAe1LGAZAyBB+y1GZn1il7ugJIflfIplcgiA0wPPahy+ApYJRf/uGL+y8n82gH7D2do7yv5a8BDFEN4NQuRnz2bI=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: dev-mysecret