apiVersion: apps/v1
kind: Deployment
metadata:
  name: surote-py-header
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: surote-py-header
          image: quay.io/rh_ee_swongpai/py-http-header:c8c64e133f9c834b5e72c03a7d58e1acd4351b19
          envFrom:
            - secretRef:
                name: demo-kus
            - configMapRef:
                name: sealed-secret-trigger
