apiVersion: apps/v1
kind: Deployment
metadata:
  name: surote-py-header
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: surote-py-header
          image: quay.io/rh_ee_swongpai/py-http-header:6962b4d6ba351b3fd10b5dfc61b306de36d74777
          envFrom:
            - secretRef:
                name: demo-kus
            - configMapRef:
                name: sealed-secret-trigger
