apiVersion: apps/v1
kind: Deployment
metadata:
  name: surote-py-header
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: surote-py-header
          image: quay.io/rh_ee_swongpai/py-http-header:3222ddf3ae80319e3f4d2c5cf671028d0aeec04a
          envFrom:
            - secretRef:
                name: demo-kus
            - configMapRef:
                name: sealed-secret-trigger
