apiVersion: apps/v1
kind: Deployment
metadata:
  name: surote-py-header
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: surote-py-header
          image: quay.io/rh_ee_swongpai/py-http-header:68d85bc121c53d363b353bb7e4242eeebf5a27be
          envFrom:
            - secretRef:
                name: demo-kus
            - configMapRef:
                name: sealed-secret-trigger
