resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
patches:
- path: deployment.yaml
- path: route-app.yaml

configMapGenerator:
  - name: env
    envs:
      - env.conf

namespace: surote-demo-dev