resources:
- ../../base
- demo-sealed-secret.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- path: deployment.yaml
- path: route-app.yaml

configMapGenerator:
  - name: env
    envs:
      - env.conf
  - name: sealed-secret-trigger
    files:
    - demo-sealed-secret.yaml

configurations:
  - configuration/name-reference.yaml