resources:
- ../../base
- demo-sealed-secret.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
patches:
- path: deployment.yaml
- path: route-app.yaml

configMapGenerator:
  - name: env
    envs:
      - env.conf
  - name: sealed-secret-trigger
    files:
    - demo-sealed-secret.yaml

generatorOptions:
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    currently-used-by-kustomize: "true"

secretGenerator:
  - name: dev-mysecret
    type: opaque



namespace: surote-demo-dev