apiVersion: apps/v1
kind: Deployment
metadata:
  name: surote-py-header
  labels:
    app: surote-py-header
spec:
  selector:
    matchLabels:
      app: surote-py-header
  template:
    metadata:
      labels:
        app: surote-py-header
    spec:
      containers:
        - name: surote-py-header
          image: surote/py-http-echo
          ports:
            - containerPort: 8080
          env:
            - name: BE_URL
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: BE_URL
            - name: dev-mysecret
              valueFrom:
                secretKeyRef:
                  name: dev-mysecret
                  key: foo